# Project information
site_name: ASI Payment Gateway For SaaS Products (IDEATION)
site_url: https://aitrenches.github.io/asi-gateway
site_author: Trenches AI
site_description: >-
  TODO

# Repository
repo_name: aitrenches/asi-gateway
repo_url: https://github.com/aitrenches/asi-gateway

# Site Configuration
theme:
  name: material
  language: en

  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    - navigation.expand
    - navigation.path
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo # The primary color is used for the header, the sidebar, text links and several other components.
      accent: indigo # The accent color is used to denote elements that can be interacted with, e.g. hovered links, buttons and scrollbars.
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to light mode
    
  font:
    text: Roboto
    code: Roboto Mono

# Specify the order manually in the 'nav' section
nav:
  - Methodology: 'index.md'
  - Existing Solutions: '1-existing-solutions.md'
  - Key Features: '2-key-features.md'
  - Challenges: '3-challenges.md'
  - Market Trends in Crypto Payment Gateways: '4-mkt-trends.md'
  - Competitor Analysis: '5-competitor-analysis.md'
  - Survey Responses: '6-survey-responses.md'
  - Competitive Analysis: '8-competitive-analysis.md'
  - User Persona: '9-user-persona.md'
  - Market Sizing: '10-market-sizing.md'
  - Regulatory Landscape: '11-regulatory-landscape.md'
  - Trend Analysis: '12-trend-analysis.md'
  - SWOT Analysis: '13-swot-analysis.md'
  - User Journey Mapping: '14-usr-journey-mapping.md'
  - Benchmark Study: '15-benchmark-study.md'
  - Feasibility Study: 'FEASIBILITY-STUDY.md'
  - Architecture: 'ARCHITECTURE.md'
  - Roadmap: 'ROADMAP.md'
  - Landing Page: 'LANDING-PAGE.md'
  - Prototype: 'PROROTYPE.md'

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aitrenches
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/trenches_ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/trenches-ai/

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: |
  &copy; 2023 <a href="https://trenches.ai"  target="_blank" rel="noopener">Trenches AI</a>
