site_name: ASI Payment Gateway For SaaS Products (IDEATION)
site_url: https://aitrenches.github.io/asi-gateway
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

# Specify the order manually in the 'nav' section
nav:
  - Methodology: 'index.md'
  - Existing Solutions: '1-existing-solutions.md'
  - Key Features: '2-key-features.md'
  - Challenges: '3-challenges.md'
  - Market Trends in Crypto Payment Gateways: '4-mkt-trends.md'
  - Competitor Analysis: '5-competitor-analysis.md'
  - Survey Responses: '6-survey-responses.md'
  - Interviews: '7-interviews.md'
  - Competitive Analysis: '8-competitive-analysis.md'
  - User Persona: '9-user-persona.md'
  - Market Sizing: '10-market-sizing.md'
  - Regulatory Landscape: '11-regulatory-landscape.md'
  - Trend Analysis: '12-trend-analysis.md'
  - SWOT Analysis: '13-swot-analysis.md'
  - User Journey Mapping: '14-usr-journey-mapping.md'
  - Benchmark Study: '15-benchmark-study.md'
  - Feasibility Study: 'FEASIBILITY-STUDY.md'
  - Architecture: 'ARCHITECTURE.md'
  - Roadmap: 'ROADMAP.md'

plugins:
  - social
  - search

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aitrenches
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/trenches_ai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/trenches-ai/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

copyright: |
  &copy; 2023 <a href="https://trenches.ai"  target="_blank" rel="noopener">Trenches AI</a>
